services:
  postgres:
    image: postgres:latest
    container_name: hotela-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: hotela
      TZ: "UTC"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - hotela-network

networks:
  hotela-network:
    driver: bridge

volumes:
  pgdata: