app:
  datasource:
    schema: hotela

spring:
  application:
    name: hotela

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/hotela
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    url: jdbc:postgresql://localhost:5432/hotela
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml

logging:
  level:
    liquibase: DEBUG

security:
  key: ${JWT_SECRET:12345678901234567890123456789012}

server:
  port: 51511