app:
  datasource:
    schema: hotela

spring:
  application:
    name: hotela

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:5432/services
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none

  liquibase:
    url: jdbc:postgresql://${DB_HOST}:5432/services
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    enabled: false
    change-log: classpath:/db/changelog/db.changelog-master.yaml

logging:
  level:
    liquibase: DEBUG

security:
  key: ${JWT_SECRET}