spring:
    application:
        name: hotela

    datasource:
        # Replace h2 to postgresql after configuring the database
        # url: jdbc:h2:mem:testdb
        # username: sa
        # password:
        url: jdbc:postgresql://localhost:${DB_HOST_PORT}/${DB_NAME}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver

    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.yaml
        enabled: true

    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                format_sql: false
                show_sql: false
                generate_statistics: false
        defer-datasource-initialization: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect

    sql:
        init:
            mode: never

logging:
    level:
        org.hibernate.SQL: OFF
        com.zaxxer.hikari: OFF

app:
    jwt:
        secret: ${APP_JWT_SECRET}
        expiration-ms: ${APP_JWT_EXPIRATION_MS}
        issuer: HotelaApp
