name: Java CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Grant execute permission for Gradle wrapper
        if: runner.os != 'Windows'
        run: chmod +x gradlew

      - name: Run code formatting check (Spotless)
        run: ./gradlew spotlessCheck
        shell: bash

      - name: Run all tests
        run: ./gradlew test jacocoTestReport
        shell: bash