name: Java CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    pipeline:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"

            - name: Grant execute permission for Gradle wrapper
              if: runner.os != 'Windows'
              run: chmod +x gradlew

            - name: Run code formatting check (Spotless)
              run: ./gradlew spotlessCheck

            - name: Run tests with gradle
              run: ./gradlew test
